/**
 * ChoroplethMap — DMV county map colored by a chosen metric.
 *
 * STATUS: stub. Implement in step 8 of PROJECT_SPEC.
 *
 * Behavior to build:
 *   - Load /data/geo/dmv-counties.geojson (generated by scripts/prep-geojson.ts).
 *   - Use MapLibre GL JS with free OSM raster tiles.
 *   - Color each county polygon by a metric value (default: FHFA HPI YoY).
 *   - Tooltip on hover: county name + metric value.
 *   - Click a county → navigate to /county/{fips}.
 *   - Legend in the corner showing the color scale.
 *   - Mobile-responsive height (300px on phone, 480px on desktop).
 */

export function ChoroplethMap() {
  return (
    <div className="rounded-lg border border-dashed border-neutral-300 p-12 text-center text-neutral-500">
      Choropleth map — coming in step 8
    </div>
  );
}
