import type { Config } from 'tailwindcss';

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'paper-50': 'var(--paper-50)',
        'paper-100': 'var(--paper-100)',
        'paper-200': 'var(--paper-200)',
        'paper-300': 'var(--paper-300)',
        'paper-400': 'var(--paper-400)',
        'paper-500': 'var(--paper-500)',
        'paper-600': 'var(--paper-600)',
        'paper-700': 'var(--paper-700)',
        'paper-800': 'var(--paper-800)',
        'paper-900': 'var(--paper-900)',
        'crab-50': 'var(--crab-50)',
        'crab-100': 'var(--crab-100)',
        'crab-200': 'var(--crab-200)',
        'crab-300': 'var(--crab-300)',
        'crab-400': 'var(--crab-400)',
        'crab-500': 'var(--crab-500)',
        'crab-600': 'var(--crab-600)',
        'crab-700': 'var(--crab-700)',
        'crab-800': 'var(--crab-800)',
        'crab-900': 'var(--crab-900)',
        'gold-50': 'var(--gold-50)',
        'gold-100': 'var(--gold-100)',
        'gold-200': 'var(--gold-200)',
        'gold-300': 'var(--gold-300)',
        'gold-400': 'var(--gold-400)',
        'gold-500': 'var(--gold-500)',
        'gold-600': 'var(--gold-600)',
        'gold-700': 'var(--gold-700)',
        'ink-900': 'var(--ink-900)',
        'green-50': 'var(--green-50)',
        'green-500': 'var(--green-500)',
        'green-700': 'var(--green-700)',
        'amber-50': 'var(--amber-50)',
        'amber-500': 'var(--amber-500)',
        'amber-700': 'var(--amber-700)',
        'red-50': 'var(--red-50)',
        'red-500': 'var(--red-500)',
        'red-700': 'var(--red-700)',
        'blue-50': 'var(--blue-50)',
        'blue-500': 'var(--blue-500)',
        'blue-700': 'var(--blue-700)',
        primary: 'var(--primary)',
        accent: 'var(--accent)',
        'bg-paper': 'var(--bg-paper)',
        'bg-deep': 'var(--bg-deep)',
        'bg-soft': 'var(--bg-soft)',
        'surface-1': 'var(--surface-1)',
        'surface-2': 'var(--surface-2)',
        'fg-1': 'var(--fg-1)',
        'fg-2': 'var(--fg-2)',
        'fg-3': 'var(--fg-3)',
        'border-soft': 'var(--border-soft)',
        'border-strong': 'var(--border-strong)',
        success: 'var(--success)',
        warning: 'var(--warning)',
        danger: 'var(--danger)',
        info: 'var(--info)',
        // jurisdiction back-compat aliases
        dc: 'var(--crab-500)',
        md: 'var(--gold-500)',
        va: 'var(--blue-500)',
      },
      fontFamily: {
        display: ['var(--font-display)'],
        sans: ['var(--font-body)'],
        mono: ['var(--font-mono)'],
      },
      fontSize: {
        xs: ['var(--fs-xs)', { lineHeight: '1.4' }],
        sm: ['var(--fs-small)', { lineHeight: '1.55' }],
        base: ['var(--fs-body)', { lineHeight: '1.55' }],
        h4: ['var(--fs-h4)', { lineHeight: '1.35' }],
        h3: ['var(--fs-h3)', { lineHeight: '1.35' }],
        h2: ['var(--fs-h2)', { lineHeight: '1.2' }],
        h1: ['var(--fs-h1)', { lineHeight: '1.15' }],
        'display-md': ['var(--fs-display-md)', { lineHeight: '1.2' }],
        'display-lg': ['var(--fs-display-lg)', { lineHeight: '1.2' }],
        'display-xl': ['var(--fs-display-xl)', { lineHeight: '1.2' }],
      },
      spacing: {
        1: 'var(--space-1)',
        2: 'var(--space-2)',
        3: 'var(--space-3)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        7: 'var(--space-7)',
        8: 'var(--space-8)',
        9: 'var(--space-9)',
        10: 'var(--space-10)',
        11: 'var(--space-11)',
        12: 'var(--space-12)',
      },
      borderRadius: {
        xs: 'var(--radius-xs)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        full: 'var(--radius-pill)',
      },
      boxShadow: {
        1: 'var(--shadow-1)',
        2: 'var(--shadow-2)',
        3: 'var(--shadow-3)',
        focus: 'var(--shadow-focus)',
      },
      maxWidth: {
        container: '1280px',
        reading: 'var(--reading-max)',
      },
    },
  },
  plugins: [],
} satisfies Config;
